### PR TITLE
serde no-default-features to avoid std

### LINKED ISSUE #86: Enabling serde enables std
Building with serde feature and no_std is failing due to incorrect import in Cargo.toml: serde's default-features are enabled which enable std.

### PR DESCRIPTION
**Pull request by semenov-vladyslav**
This PR fixes #86.

### CODE REVIEW

**Review by conradoplg — APPROVED** [review]
Looks good, thanks!

**Comment by semenov-vladyslav** [comment]
Can you please do release a new version? Or when can we expect it to be released?

**Comment by conradoplg** [comment]
> Can you please do release a new version? Or when can we expect it to be released?

Of course, it should happen soon after the two open PRs are reviewed, hopefully today or tomorrow.

**Comment by conradoplg** [comment]
4.0.1 released

**Pull request merged**
